Repository NethermindEth/juno, pull requests merged in 2022-04, with the labels that each got.

#101 Feeder Getaway Client
  .github/workflows/juno-build.yml
  .github/workflows/juno-test.yml
  Makefile
  README.md
  cmd/juno/cli/root.go
  docs/docs/feeder-gateway.mdx
  docs/docs/sidebars.js
  docs/docusaurus.config.js
  go.mod
  go.sum
  internal/config/config.go
  internal/log/log.go
  pkg/feeder/feeder.go
  pkg/feeder/feederfakes/fake_http_client.go
  pkg/feeder/tests/feeder_test.go
  pkg/feeder/types.go
  pkg/rpc/client_test.go
  pkg/rpc/handle.go
  pkg/rpc/rpc_test.go
Labels: enhancement, core

#118 Update CI workflows
  .github/workflows/juno-build.yml
Labels: devops

#125 Update Geth deps to v1.10.17
  go.mod
  go.sum
Labels: devops

#142 Implement NumberOfItems for the KeyValueDb
  pkg/crypto/weierstrass/weierstrass.go
  pkg/db/db.go
  pkg/db/db_test.go
Labels: db
