Repository NethermindEth/juno, pull requests merged in 2022-05, with the labels that each got.

#143 Block Specific Database
  pkg/db/blockSpecific.go
  pkg/db/blockSpecific_test.go
  pkg/db/sortedList.go
  pkg/db/sortedList_test.go
Labels: db, core

#141 Hold the ABI
  pkg/db/abi/abi.go
  pkg/db/abi/abi_test.go
  pkg/db/abi/manager.go
  pkg/db/abi/manager_test.go
  pkg/db/abi/test_assets/ABI-1.json
  pkg/db/abi/test_assets/ABI-2.json
  pkg/db/abi/test_assets/ABI-3.json
  pkg/db/abi/test_assets/ABI-4.json
Labels: core

#146 Add Close method
  pkg/db/blockSpecific.go
  pkg/db/blockSpecific_test.go
Labels: db

#147 Remove error returns from the ABI manager
  pkg/db/abi/manager.go
  pkg/db/abi/manager_test.go
Labels: db

#129 feat: add binary trie
  pkg/crypto/pedersen/pedersen.go
  pkg/crypto/pedersen/pedersen_test.go
  pkg/crypto/pedersen/points.go
  pkg/crypto/pedersen/points.json
  pkg/store/store.go
  pkg/store/store_test.go
  pkg/trie/node.go
  pkg/trie/trie.go
  pkg/trie/trie_test.go
  pkg/trie/utils.go
Labels: core

#156 fix: fix typos
  pkg/trie/node.go
  pkg/trie/trie.go
Labels: bug, core

#163 Transaction Service
  internal/services/transactions.go
  internal/services/transactions_test.go
Labels: db, core

#158 Update Database on project
  internal/db/abi/abi.go
  internal/db/abi/abi_test.go
  internal/db/abi/manager.go
  internal/db/abi/manager_test.go
  internal/db/abi/test_assets/ABI-1.json
  internal/db/abi/test_assets/ABI-2.json
  internal/db/abi/test_assets/ABI-3.json
  internal/db/abi/test_assets/ABI-4.json
  internal/db/block_specific.go
  internal/db/block_specific_test.go
  internal/db/db.go
  internal/db/db_test.go
  internal/db/kv_storer.go
  internal/db/kv_storer_test.go
  internal/db/sorted_list.go
  internal/db/sorted_list_test.go
  internal/db/state/code.go
  internal/db/state/code_test.go
  internal/db/state/state.go
  internal/db/state/storage.go
  internal/db/state/storage_test.go
  internal/db/state/test_assets/contract-codes/Code-1.json
  internal/db/state/test_assets/contract-codes/Code-2.json
  internal/db/state/test_assets/contract-codes/Code-3.json
  internal/db/state/test_assets/contract-codes/Code-4.json
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/db/transaction/transaction.go
  internal/db/transaction_db.go
  internal/db/transaction_db_test.go
  internal/services/transactions.go
  internal/services/transactions_test.go
Labels: db, core

#171 refactor: export trie utility functions
  pkg/trie/trie.go
  pkg/trie/trie_test.go
  pkg/trie/utils.go
Labels: enhancement, core

#149 Initial implementation of block manager
  internal/db/Makefile
  internal/db/block/block.pb.go
  internal/db/block/block.proto
  internal/db/block/block_test.go
  internal/db/block/manager.go
  internal/services/block.go
  internal/services/block_test.go
Labels: core

#174 refactor: export `trie.Node`
  pkg/trie/node.go
  pkg/trie/trie.go
  pkg/trie/trie_test.go
Labels: enhancement, core

#167 Fix feeder types
  pkg/feeder/abi/abi.go
  pkg/feeder/abi/types.go
  pkg/feeder/feeder.go
  pkg/feeder/feederfakes/fake_structs.go
  pkg/feeder/tests/feeder_test.go
  pkg/feeder/tests/real_feeder_test.go
  pkg/feeder/types.go
Labels: bug

#180 Get block by number
  internal/db/block/block_test.go
  internal/db/block/manager.go
  internal/services/block.go
  internal/services/block_test.go
Labels: db, core

#182 Add Transaction Receipts
  internal/db/abi/abi.go
  internal/db/abi/abi.pb.go
  internal/db/abi/abi.proto
  internal/db/abi/abi_test.go
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/db/transaction/transaction.pb.go
  internal/db/transaction/transaction.proto
  internal/services/abi_test.go
  internal/services/transactions.go
  internal/services/transactions_test.go
Labels: db, core
