Repository NethermindEth/juno, pull requests merged in 2022-06, with the labels that each got.

#186 Add checks for not found
  internal/db/block/manager.go
  internal/db/state/storage.go
  internal/db/transaction/manager.go
Labels: db, core

#187 Check if the service is running on AddProcess
  internal/services/service.go
Labels: core

#189 Add a common package to manage Felt type encodings and decodings
  pkg/common/bytes.go
  pkg/common/felt.go
  pkg/common/felt_test.go
Labels: core

#192 [RPC] GetBlock
  internal/db/block/block_test.go
  internal/db/block/manager.go
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/db/transaction/transaction.pb.go
  internal/db/transaction/transaction.proto
  internal/services/block.go
  internal/services/block_test.go
  internal/services/transactions.go
  internal/services/transactions_test.go
  pkg/common/hex.go
  pkg/common/hex_test.go
  pkg/rpc/api.go
  pkg/rpc/api_test.go
  pkg/rpc/rpc_tests.json
  pkg/rpc/types.go
  pkg/types/address.go
  pkg/types/block.go
  pkg/types/eth.go
  pkg/types/event.go
  pkg/types/felt.go
  pkg/types/felt_test.go
  pkg/types/message.go
  pkg/types/transaction.go
Labels: rpc api

#208 Fix state commitment issue on L1 sync
  pkg/starknet/state.go
  pkg/starknet/types/types.go
Labels: bug, core, L1

#209 [RPC] Get Transaction
  pkg/rpc/api.go
  pkg/rpc/api_test.go
  pkg/rpc/rpc_tests.json
  pkg/rpc/types.go
  pkg/types/transaction.go
Labels: rpc api

#216 Named Database
  internal/db/named_db.go
  internal/db/named_db_test.go
Labels: db

#183 Sync Against L1 and API
  .github/workflows/juno-build.yml
  .gitignore
  README.md
  cmd/juno/cli/root.go
  cmd/juno/main.go
  docs/docs/features/sync.mdx
  go.mod
  go.sum
  internal/config/config.go
  internal/db/db.go
  internal/db/db_test.go
  internal/services/abi.go
  internal/services/block.go
  internal/services/contractHash.go
  internal/services/state.go
  internal/services/transactions.go
  pkg/feeder/abi/abi.go
  pkg/feeder/feeder.go
  pkg/feeder/feeder_test.go
  pkg/feeder/types.go
  pkg/rpc/server.go
  pkg/starknet/abi/abi.go
  pkg/starknet/abi/gps_verifier_abi.json
  pkg/starknet/abi/memory_pages_abi.json
  pkg/starknet/abi/starknet_abi.json
  pkg/starknet/abi/test_abi.json
  pkg/starknet/state.go
  pkg/starknet/state_test.go
  pkg/starknet/types/map.go
  pkg/starknet/types/map_test.go
  pkg/starknet/types/types.go
  pkg/starknet/utils.go
  pkg/starknet/utils_test.go
Labels: enhancement, core, L1

#210 Feature/metrics
  cmd/juno/cli/root.go
  docs/docs/features/metrics.mdx
  go.mod
  go.sum
  internal/config/config.go
  internal/metrics/prometheus/metrics.go
  pkg/feeder/feeder.go
  pkg/starknet/state.go
Labels: enhancement

#217 Change services to use NamedDatabase
  cmd/juno/cli/root.go
  internal/db/abi/abi_test.go
  internal/db/abi/manager_test.go
  internal/db/block/block_test.go
  internal/db/block_specific.go
  internal/db/named_db.go
  internal/db/named_db_test.go
  internal/db/state/storage_test.go
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/db/transaction_db.go
  internal/services/abi.go
  internal/services/abi_test.go
  internal/services/block.go
  internal/services/block_test.go
  internal/services/contractHash.go
  internal/services/state.go
  internal/services/state_test.go
  internal/services/transactions.go
  internal/services/transactions_test.go
  pkg/rpc/api_test.go
  pkg/starknet/state.go
  pkg/starknet/state_test.go
  pkg/starknet/utils.go
  pkg/starknet/utils_test.go
Labels: db

#223 fix: fix typos
  README.md
Labels: documentation

#220 Rpc/pending blocks
  .github/contributors.svg
  cmd/juno/cli/root.go
  internal/db/abi/manager.go
  internal/services/service.go
  pkg/feeder/types.go
  pkg/rpc/api.go
  pkg/rpc/api_test.go
  pkg/rpc/rpc_test.go
  pkg/rpc/rpc_tests.json
  pkg/rpc/server.go
  pkg/rpc/types.go
  pkg/starknet/state.go
Labels: rpc api

#234 Fix default datadir on linux
  internal/config/config.go
Labels: bug

#244 Fix type cast bug
  pkg/rpc/types.go
Labels: bug

#226 Refactor Database
  cmd/juno/cli/root.go
  docs/docs/features/database.mdx
  internal/db/abi/manager.go
  internal/db/abi/manager_test.go
  internal/db/block/block_test.go
  internal/db/block/manager.go
  internal/db/block_specific.go
  internal/db/block_specific_test.go
  internal/db/db.go
  internal/db/db_test.go
  internal/db/kv_storer.go
  internal/db/kv_storer_test.go
  internal/db/mdbx.go
  internal/db/mdbx_env.go
  internal/db/mdbx_test.go
  internal/db/named_db.go
  internal/db/state/code_test.go
  internal/db/state/state.go
  internal/db/state/storage_test.go
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/db/transaction_db.go
  internal/db/transaction_db_test.go
  internal/services/abi.go
  internal/services/abi_test.go
  internal/services/block.go
  internal/services/block_test.go
  internal/services/contractHash.go
  internal/services/service.go
  internal/services/state.go
  internal/services/state_test.go
  internal/services/transactions.go
  internal/services/transactions_test.go
  pkg/rpc/api_test.go
  pkg/starknet/state.go
  pkg/starknet/state_test.go
  pkg/starknet/types/map.go
  pkg/starknet/types/map_test.go
  pkg/starknet/utils.go
  pkg/starknet/utils_test.go
Labels: db
