Repository NethermindEth/juno, pull requests merged in 2022-08, with the labels that each got.

#307 Set test coverage threshold
  .github/codecov.yml
Labels: devops

#310 Update codecov settings
  .github/codecov.yml
Labels: devops

#319 Update RPC Felt regexp
  internal/rpc/starknet/utils.go
Labels: rpc api

#320 Upgrade docusaurus
  docs/.gitignore
  docs/.yarnrc.yml
  docs/README.md
  docs/package.json
  docs/yarn.lock
Labels: documentation

#322 Use proper yarn version in github workflow
  .github/workflows/docs-prod-deploy.yml
Labels: devops

#295 refactor config
  .github/workflows/juno-build.yml
  Dockerfile
  Makefile
  cmd/juno-cli/cli/root.go
  cmd/juno/cli/create_dynamic_config.go
  cmd/juno/cli/long.txt
  cmd/juno/cli/root.go
  cmd/juno/configure.go
  cmd/juno/main.go
  docs/docs/intro.md
  docs/docs/running/config.mdx
  docs/docs/running/useful-commands.mdx
  internal/cairovm/vm.go
  internal/cairovm/vm_test.go
  internal/config/config.go
  internal/config/config_test.go
  internal/sync/sync.go
  pkg/rest/handler.go
  pkg/rest/tests/rest_test.go
Labels: cli

#330 Fix missing constructor_calldata field
  internal/sync/sync.go
  pkg/feeder/types.go
Labels: core

#325 Pull Go 1.19 changes into signature libraries
  pkg/crypto/signature/signature.go
  pkg/crypto/signature/signature_test.go
  pkg/crypto/weierstrass/stark.go
  pkg/crypto/weierstrass/weierstrass.go
  pkg/crypto/weierstrass/weierstrass_test.go
Labels: documentation, crypto

#341 Fix rpc get_storageAt
  cmd/juno/main.go
  internal/rpc/starknet/starknet.go
Labels: rpc

#349 Update db max to 4tb
  internal/db/mdbx_env.go
Labels: db

#343 Fix typo on starknet rpc method
  cmd/juno/main.go
Labels: bug, rpc

#332 Fix rpc and sync process DEPLOY transaction type
  go.mod
  internal/db/transaction/manager.go
  internal/db/transaction/manager_test.go
  internal/rpc/starknet/types.go
  internal/sync/sync.go
  pkg/feeder/types.go
  pkg/types/transaction.go
Labels: bug, rpc

#337 Remove --sync-trustless config param
  cmd/juno/configure.go
  cmd/juno/main.go
  docs/docs/intro.md
  docs/docs/running/config.mdx
  internal/config/config.go
  internal/sync/sync.go
Labels: cli

#360 Fix RPC bugs
  cmd/juno/main.go
  docs/docs/features/rpc.mdx
  internal/rpc/starknet/errors.go
  internal/rpc/starknet/starknet.go
  internal/rpc/starknet/types.go
  internal/rpc/starknet/utils.go
  pkg/jsonrpc/error.go
Labels: rpc

#370 Bug on starknet_call
  cmd/juno/main.go
  internal/cairovm/vm.go
  internal/cairovm/vm_test.go
  internal/cairovm/vmrpc/vm.go
  internal/cairovm/vmrpc/vm.pb.go
  internal/cairovm/vmrpc/vm.proto
  internal/cairovm/vmrpc/vm.py
  internal/cairovm/vmrpc/vm_pb2.py
  internal/rpc/starknet/starknet.go
Labels: bug

#371 Sync store info order
  internal/sync/sync.go
  pkg/feeder/feeder.go
Labels: bug, core

#373 Update docker-image CI workflow
  .github/workflows/docker-image.yml
Labels: devops

#374 Reduce docker image size on build
  Dockerfile
Labels: enhancement

#379 Fix on nil pointer after connection broken with the Feeder gateway
  pkg/feeder/feeder.go
Labels: bug
