Repository NethermindEth/juno, pull requests merged in 2024-08, with the labels that each got.

#2009 feat: move compilation of native contracts into Juno
  vm/rust/Cargo.toml
  vm/rust/src/juno_state_reader.rs
Labels: cairo native

#1882 Sort buffered transactions
  core/state.go
Labels: Optimisation, DB

#2034 feat: persist native compiled contracts
  vm/rust/Cargo.toml
  vm/rust/build.rs
  vm/rust/src/juno_state_reader.rs
  vm/rust/src/lib.rs
Labels: cairo native

#2030 Daniil/rust-linter-issues-fix
  core/rust/src/lib.rs
  starknet/compiler.go
  starknet/rust/src/lib.rs
  vm/rust/src/juno_state_reader.rs
  vm/rust/src/lib.rs
  vm/rust/src/versioned_constants.rs
Labels: go, rust

#2050 revert docs v0.12.0 as subcommands are not supported
  docs/versioned_docs/version-0.12.0/_config-options.md
  docs/versioned_docs/version-0.12.0/configuring.md
  docs/versioned_docs/version-0.12.0/faq.md
  docs/versioned_docs/version-0.12.0/hardware-requirements.md
  docs/versioned_docs/version-0.12.0/intro.md
  docs/versioned_docs/version-0.12.0/json-rpc.md
  docs/versioned_docs/version-0.12.0/monitoring.md
  docs/versioned_docs/version-0.12.0/running-juno.md
  docs/versioned_docs/version-0.12.0/running-on-gcp.md
  docs/versioned_docs/version-0.12.0/running-p2p.md
  docs/versioned_docs/version-0.12.0/snapshots.md
  docs/versioned_docs/version-0.12.0/updating.md
  docs/versioned_docs/version-0.12.0/websocket.md
  docs/versioned_sidebars/version-0.12.0-sidebars.json
  docs/versions.json
Labels: Documentation

#2081 Update `blockifier` to 0.8.0-rc.2
  starknet/rust/Cargo.toml
  vm/rust/Cargo.toml
Labels: dependencies

#2083 Record and benchmark traces with Juno
  .gitignore
  vm/rust/Cargo.toml
  vm/rust/benches/README.md
  vm/rust/benches/blockifier-perf.rs
  vm/rust/src/bin/trace_block.rs
  vm/rust/src/juno_state_reader.rs
  vm/rust/src/lib.rs
  vm/rust/src/recorded_state.rs
Labels: cairo native
