Repository NethermindEth/juno, pull requests merged in 2025-06, with the labels that each got.

#2754 feat(node): hash scheme for TrieDB
  core/accessors.go
  core/trie2/databasetest.go
  core/trie2/trie.go
  core/trie2/trie_test.go
  core/trie2/triedb/database.go
  core/trie2/triedb/hashdb/clean_cache.go
  core/trie2/triedb/hashdb/database.go
  core/trie2/triedb/hashdb/database_test.go
  core/trie2/triedb/hashdb/dirty_cache.go
  core/trie2/triedb/hashdb/utils.go
  core/trie2/trieutils/accessors.go
  core/trie2/trieutils/bitarray.go
  db/buckets.go
  db/schema.go
Labels: New DB

#2860 refactor: Add Commit action
  consensus/driver/driver.go
  consensus/driver/driver_test.go
  consensus/integtest/blockchain.go
  consensus/integtest/integ_test.go
  consensus/starknet/starknet.go
  consensus/tendermint/action_builder_test.go
  consensus/tendermint/process.go
  consensus/tendermint/rule_commit_value.go
  consensus/tendermint/rule_commit_value_test.go
  consensus/tendermint/tendermint.go
  consensus/tendermint/tendermint_test.go
  consensus/tendermint/wal_test.go
  consensus/types/action.go
Labels: Tendermint

#2866 feat: event query acceleration
  blockchain/aggregated_bloom_filter_cache.go
  blockchain/aggregated_bloom_filter_cache_test.go
  blockchain/blockchain.go
  blockchain/event_filter.go
  blockchain/event_matcher.go
  core/accessors.go
  core/aggregated_bloom_filter.go
  core/aggregated_bloom_filter_test.go
  core/running_event_filter.go
  core/running_event_filter_test.go
  core/transaction.go
  db/buckets.go
  db/buckets_enumer.go
  db/schema.go
  migration/migration.go
  mocks/mock_blockchain.go
  node/node.go
  rpc/v6/events_test.go
Labels: High priority

#2851 feature: implement the consensus Validator interface
  blockchain/blockchain.go
  builder/builder.go
  cmd/juno/juno.go
  cmd/juno/juno_test.go
  consensus/mocks/mock_validator.go
  consensus/tendermint/rule_proposal_and_polka_previous.go
  consensus/types/tmp.go
  consensus/validator/init_test.go
  consensus/validator/validator.go
  consensus/validator/validator_test.go
  core/block.go
  sequencer/sequencer_test.go
  sequencer/sequencer_utils.go
Labels: Tendermint

#2839 feat: Add scaffolding for proposal state machine
  consensus/p2p/validator/state_machine.go
  consensus/p2p/validator/state_machine_test.go
  consensus/p2p/validator/transition.go
  consensus/p2p/validator/validator_utils_test.go
Labels: Tendermint

#2875 feat: Add proposal stream with ability to reorder messages
  consensus/p2p/validator/proposal_stream.go
  consensus/p2p/validator/proposal_stream_test.go
Labels: Tendermint

#2874 feat: Add general buffered topic subscription
  consensus/p2p/buffered/buffered_topic_subscription.go
  consensus/p2p/buffered/buffered_topic_subscription_test.go
  consensus/p2p/config/config.go
Labels: Tendermint

#2878 test: Improve proposal stream test readability
  consensus/p2p/validator/proposal_stream_test.go
Labels: Tendermint

#2876 feat: Add proposal stream demux with ability to process multiple streams
  consensus/p2p/validator/proposal_stream.go
  consensus/p2p/validator/proposal_stream_demux.go
  consensus/p2p/validator/proposal_stream_demux_test.go
Labels: Tendermint

#2896 feat: Implement general buffered proto broadcaster
  consensus/p2p/buffered/buffered_test.go
  consensus/p2p/buffered/proto_broadcaster.go
  consensus/p2p/buffered/topic_subscription.go
Labels: Tendermint

#2916 tendermint: adapters for validator
  adapters/p2p2consensus/proposal.go
  adapters/p2p2consensus/transaction.go
  adapters/p2p2consensus/validation.go
  core/felt/felt.go
Labels: Tendermint

#2920 feat: Implement simple proposer store
  consensus/proposal/proposal_store.go
  consensus/proposal/proposal_store_test.go
Labels: Tendermint

#2929 fix: Add correct calculation for gas price in Fri
  builder/builder.go
  consensus/proposer/proposer.go
  consensus/validator/validator.go
  consensus/validator/validator_test.go
Labels: Tendermint

#2935 feat: Connect validator block execution
  clients/feeder/testdata/sepolia-integration/block/1164607.json
  clients/feeder/testdata/sepolia-integration/block/1164608.json
  clients/feeder/testdata/sepolia-integration/block/1164609.json
  clients/feeder/testdata/sepolia-integration/block/1164610.json
  clients/feeder/testdata/sepolia-integration/block/1164617.json
  clients/feeder/testdata/sepolia-integration/block/1164618.json
  clients/feeder/testdata/sepolia-integration/block/1164619.json
  clients/feeder/testdata/sepolia-integration/block/1164620.json
  clients/feeder/testdata/sepolia-integration/block/1164621.json
  clients/feeder/testdata/sepolia-integration/signature/1164607.json
  clients/feeder/testdata/sepolia-integration/signature/1164608.json
  clients/feeder/testdata/sepolia-integration/signature/1164609.json
  clients/feeder/testdata/sepolia-integration/signature/1164610.json
  clients/feeder/testdata/sepolia-integration/signature/1164617.json
  clients/feeder/testdata/sepolia-integration/signature/1164618.json
  clients/feeder/testdata/sepolia-integration/signature/1164619.json
  clients/feeder/testdata/sepolia-integration/signature/1164620.json
  clients/feeder/testdata/sepolia-integration/signature/1164621.json
  clients/feeder/testdata/sepolia-integration/state_update_with_block/1164618.json
  consensus/p2p/validator/compare_test.go
  consensus/p2p/validator/init_test.go
  consensus/p2p/validator/proposal_stream.go
  consensus/p2p/validator/proposal_stream_demux.go
  consensus/p2p/validator/proposal_stream_demux_test.go
  consensus/p2p/validator/proposal_stream_test.go
  consensus/p2p/validator/state_machine.go
  consensus/p2p/validator/state_machine_test.go
  consensus/p2p/validator/transition.go
  consensus/p2p/validator/transition_test.go
  consensus/validator/validator.go
  consensus/validator/validator_test.go
Labels: Tendermint

#2932 tests: Add fixtures for state machine based on real block
  clients/feeder/testdata/sepolia-integration/block/1164607.json
  clients/feeder/testdata/sepolia-integration/block/1164608.json
  clients/feeder/testdata/sepolia-integration/block/1164609.json
  clients/feeder/testdata/sepolia-integration/block/1164610.json
  clients/feeder/testdata/sepolia-integration/block/1164617.json
  clients/feeder/testdata/sepolia-integration/block/1164618.json
  clients/feeder/testdata/sepolia-integration/block/1164619.json
  clients/feeder/testdata/sepolia-integration/block/1164620.json
  clients/feeder/testdata/sepolia-integration/block/1164621.json
  clients/feeder/testdata/sepolia-integration/signature/1164607.json
  clients/feeder/testdata/sepolia-integration/signature/1164608.json
  clients/feeder/testdata/sepolia-integration/signature/1164609.json
  clients/feeder/testdata/sepolia-integration/signature/1164610.json
  clients/feeder/testdata/sepolia-integration/signature/1164617.json
  clients/feeder/testdata/sepolia-integration/signature/1164618.json
  clients/feeder/testdata/sepolia-integration/signature/1164619.json
  clients/feeder/testdata/sepolia-integration/signature/1164620.json
  clients/feeder/testdata/sepolia-integration/signature/1164621.json
  clients/feeder/testdata/sepolia-integration/state_update_with_block/1164618.json
  consensus/p2p/validator/compare_test.go
  consensus/p2p/validator/empty_fixtures_test.go
  consensus/p2p/validator/fixtures_test.go
  consensus/p2p/validator/init_test.go
  consensus/p2p/validator/mock_executor_test.go
  consensus/p2p/validator/proposal_stream.go
  consensus/p2p/validator/proposal_stream_demux.go
  consensus/p2p/validator/proposal_stream_demux_test.go
  consensus/p2p/validator/proposal_stream_test.go
  consensus/p2p/validator/state_machine.go
  consensus/p2p/validator/state_machine_test.go
  consensus/p2p/validator/transition.go
  consensus/p2p/validator/transition_test.go
  consensus/validator/validator.go
  consensus/validator/validator_test.go
Labels: Tendermint
