Repository NethermindEth/juno, pull requests merged in 2025-03, with the labels that each got.

#2583 fix: VM fee issue due to selection of wrong versioned constants
  vm/rust/src/lib.rs
Labels: Bug, High priority

#2588 refactor: rename `Ptr` utility to `HeapPtr`
  adapters/core2p2p/receipt.go
  adapters/p2p2core/receipt_test.go
  clients/feeder/feeder_test.go
  p2p/p2p.go
  rpc/v6/block_test.go
  rpc/v6/chain_test.go
  rpc/v6/class_test.go
  rpc/v6/contract_test.go
  rpc/v6/estimate_fee_test.go
  rpc/v6/events_test.go
  rpc/v6/handlers_test.go
  rpc/v6/simulation.go
  rpc/v6/simulation_test.go
  rpc/v6/state_update_test.go
  rpc/v6/sync_test.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v6/transaction.go
  rpc/v6/transaction_test.go
  rpc/v7/block_test.go
  rpc/v7/estimate_fee_test.go
  rpc/v7/handlers_test.go
  rpc/v7/simulation.go
  rpc/v7/simulation_test.go
  rpc/v7/storage_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v7/transaction.go
  rpc/v7/transaction_test.go
  rpc/v8/block_test.go
  rpc/v8/estimate_fee_test.go
  rpc/v8/simulation.go
  rpc/v8/simulation_pkg_test.go
  rpc/v8/simulation_test.go
  rpc/v8/subscriptions_test.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
  utils/ptr.go
  vm/transaction.go
Labels: Refactor

#2509 Refactor: Reuse v6 juno_unsubscribe handler for v7 and v8 (starknet_unsubscribe)
  rpc/handlers.go
  rpc/v6/events_test.go
  rpc/v7/events.go
  rpc/v8/handlers.go
  rpc/v8/subscriptions.go
  rpc/v8/subscriptions_test.go
Labels: RPC, Refactor

#2584 fix(rpc): failed fee estimation due to absence of l1_data_gas
  adapters/sn2core/sn2core.go
  core/transaction.go
  starknetdata/feeder/feeder_test.go
Labels: Bug, High priority

#2607 fix: Return correct error for getStorageProof on pending block
  rpc/v8/storage.go
  rpc/v8/storage_test.go
Labels: Bug

#2612 refactor: Use a common function for send subscription response
  rpc/v8/subscriptions.go
Labels: RPC, Refactor

#2601 fix(rpc): failed json marshalling in starknet_call rpc v6-7
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
Labels: Bug, High priority

#2611 Add 'L1_DATA_GAS' missing field from marshal func of the 'starknet.Resource' type
  adapters/sn2core/sn2core_test.go
  clients/feeder/feeder_test.go
  clients/feeder/testdata/integration/transaction/0x29fd7881f14380842414cdfdd8d6c0b1f2174f8916edcfeb1ede1eb26ac3ef0.json
  clients/feeder/testdata/integration/transaction/0x41d1f5206ef58a443e7d3d1ca073171ec25fa75313394318fc83a074a6631c3.json
  clients/feeder/testdata/integration/transaction/0x49728601e0bb2f48ce506b0cbd9c0e2a9e50d95858aa41463f46386dca489fd.json
  clients/feeder/testdata/sepolia/transaction/0x30c852c522274765e1d681bc8a84ce7c41118370ef2ba7d18a427ed29f5b155.json
  clients/feeder/testdata/sepolia/transaction/0x32413f8cee053089d6d7026a72e4108262ca3cfe868dd9159bc1dd160aec975.json
  clients/feeder/testdata/sepolia/transaction/0x76b52e17bc09064bd986ead34263e6305ef3cecfb3ae9e19b86bf4f1a1a20ea.json
  core/transaction_test.go
  rpc/v8/transaction_test.go
  starknet/transaction.go
  starknet/transaction_test.go
  vm/transaction_pkg_test.go
Labels: Bug, High priority

#2602 fix(rpc/v6): extremely large `gas_consumed`
  rpc/v6/estimate_fee_test.go
  rpc/v6/simulation.go
  rpc/v6/simulation_test.go
  rpc/v7/estimate_fee.go
  rpc/v7/simulation.go
  rpc/v7/simulation_test.go
  rpc/v8/simulation.go
  rpc/v8/simulation_pkg_test.go
Labels: Bug, High priority

#2642 fix(rpcv6): Add check for pending block in TransactionReceiptByHash
  rpc/v6/transaction.go
  rpc/v6/transaction_test.go
Labels: Bug

#2650 fix(rpc): handle updated entry point not found error format
  rpc/rpccore/rpccore.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
Labels: Bug, RPC

#2371 implement logic to build genesis state for the sequencer
  adapters/vm2core/vm2core.go
  core/state_update.go
  genesis/classes/account.json
  genesis/classes/strk.json
  genesis/classes/udacnt.json
  genesis/classes/universaldeployer.json
  genesis/genesis.go
  genesis/genesis_prefund_accounts.json
  genesis/genesis_test.go
  mocks/mock_vm.go
  node/throttled_vm.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
  sync/pending.go
  vm/rust/src/jsonrpc.rs
  vm/rust/src/juno_state_reader.rs
  vm/rust/src/lib.rs
  vm/state.go
  vm/trace.go
  vm/trace_test.go
  vm/vm.go
  vm/vm_ffi.h
  vm/vm_test.go
Labels: Sequencer, 3 reviews

#2649 refactor: replace `interface{}` with `any`
  core/felt/felt.go
  l1/l1_test.go
  node/node.go
  utils/log.go
  utils/nil.go
  utils/nil_test.go
Labels: Refactor

#2648 refactor(core): replace m[k]=v loops with maps.Copy in state_test.go
  core/state_test.go
Labels: Refactor

#2496 Refactor: starknet_estimateMessageFee
  rpc/v6/transaction.go
  rpc/v7/estimate_fee.go
  rpc/v7/estimate_fee_test.go
  rpc/v7/handlers_test.go
  rpc/v7/simulation.go
  rpc/v7/simulation_test.go
  rpc/v7/transaction.go
  rpc/v8/estimate_fee.go
  rpc/v8/estimate_fee_test.go
  rpc/v8/handlers_test.go
  rpc/v8/simulation.go
  rpc/v8/simulation_test.go
  rpc/v8/transaction.go
Labels: RPC, Refactor

#2662 fix(rpc/v8): no error for empty storage keys for getStorageProof
  rpc/v8/storage.go
  rpc/v8/storage_test.go
Labels: High priority

#2660 feat(rpc/v0.8.0): change Offset type from *felt.Felt to uint64 in CasmEntryPoint
  rpc/v8/compiled_casm.go
  rpc/v8/compiled_casm_test.go
Labels: RPC

#2664 refactor(felt): organize felt and add new ctors
  core/felt/felt.go
  core/felt/felt_test.go
Labels: Refactor
