Repository NethermindEth/juno, pull requests merged in 2025-05, with the labels that each got.

#2786 test: Unit tests for Tendermint driver
  consensus/driver/driver.go
  consensus/driver/driver_test.go
  consensus/mocks/mock_state_machine.go
  consensus/tendermint/action.go
  consensus/tendermint/action_asserter_test.go
  consensus/tendermint/action_builder_test.go
  consensus/tendermint/assert_utils_test.go
  consensus/tendermint/broadcast.go
  consensus/tendermint/incoming_message_builder_test.go
  consensus/tendermint/messages.go
  consensus/tendermint/process.go
  consensus/tendermint/rule_commit_value.go
  consensus/tendermint/rule_commit_value_test.go
  consensus/tendermint/rule_first_proposal.go
  consensus/tendermint/rule_first_proposal_test.go
  consensus/tendermint/rule_polka_any.go
  consensus/tendermint/rule_polka_any_test.go
  consensus/tendermint/rule_polka_nil.go
  consensus/tendermint/rule_polka_nil_test.go
  consensus/tendermint/rule_precommit_any.go
  consensus/tendermint/rule_precommit_any_test.go
  consensus/tendermint/rule_proposal_and_polka_current.go
  consensus/tendermint/rule_proposal_and_polka_current_test.go
  consensus/tendermint/rule_proposal_and_polka_previous.go
  consensus/tendermint/rule_proposal_and_polka_previous_test.go
  consensus/tendermint/rule_skip_round.go
  consensus/tendermint/rule_skip_round_test.go
  consensus/tendermint/start_test.go
  consensus/tendermint/state_machine_context_test.go
  consensus/tendermint/tendermint.go
  consensus/tendermint/tendermint_test.go
  consensus/tendermint/timeout.go
  consensus/tendermint/timeout_test.go
Labels: Tendermint

#2821 refactor: Use iterate pattern from pebble docs
  consensus/db/db.go
Labels: Tendermint

#2822 refactor: Move timeout rules back to its separate files
  consensus/tendermint/rule_proposal_and_polka_current_test.go
  consensus/tendermint/tendermint.go
  consensus/tendermint/timeout.go
Labels: Tendermint

#2827 refactor: Move Listener and Broadcaster to p2p package
  consensus/driver/driver.go
  consensus/driver/driver_test.go
  consensus/p2p/broadcaster.go
  consensus/p2p/listener.go
Labels: Tendermint

#2790 test: Integration tests for cluster of Tendermint drivers
  consensus/integtest/application.go
  consensus/integtest/blockchain.go
  consensus/integtest/broadcaster.go
  consensus/integtest/integ_test.go
  consensus/integtest/listener.go
  consensus/integtest/network.go
  consensus/integtest/node.go
  consensus/integtest/validator.go
  consensus/tendermint/rule_commit_value.go
  consensus/tendermint/tendermint.go
Labels: Tendermint

#2824 refactor: Use types directly from proto packages instead of via aliases
  adapters/core2p2p/block.go
  adapters/core2p2p/class.go
  adapters/core2p2p/felt.go
  adapters/core2p2p/receipt.go
  adapters/core2p2p/state.go
  adapters/core2p2p/transaction.go
  adapters/p2p2core/block.go
  adapters/p2p2core/class.go
  adapters/p2p2core/felt.go
  adapters/p2p2core/felt_test.go
  adapters/p2p2core/receipt.go
  adapters/p2p2core/receipt_test.go
  adapters/p2p2core/state.go
  adapters/p2p2core/transaction.go
  p2p/gen/class.go
  p2p/gen/common.go
  p2p/gen/sync_class.go
  p2p/gen/sync_common.go
  p2p/gen/sync_event.go
  p2p/gen/sync_header.go
  p2p/gen/sync_receipt.go
  p2p/gen/sync_state.go
  p2p/gen/sync_transaction.go
  p2p/gen/transaction.go
  p2p/peers/handlers.go
  p2p/sync/client.go
  p2p/sync/sync.go
Labels: Tendermint

#2838 refactor: create a package for real starknet types used in tendermint
  consensus/db/db_test.go
  consensus/driver/driver_test.go
  consensus/starknet/starknet.go
  consensus/tendermint/action_asserter_test.go
  consensus/tendermint/action_builder_test.go
  consensus/tendermint/assert_utils_test.go
  consensus/tendermint/incoming_message_builder_test.go
  consensus/tendermint/rule_commit_value_test.go
  consensus/tendermint/rule_first_proposal_test.go
  consensus/tendermint/rule_polka_any_test.go
  consensus/tendermint/rule_polka_nil_test.go
  consensus/tendermint/rule_precommit_any_test.go
  consensus/tendermint/rule_proposal_and_polka_current_test.go
  consensus/tendermint/rule_proposal_and_polka_previous_test.go
  consensus/tendermint/rule_skip_round_test.go
  consensus/tendermint/start_test.go
  consensus/tendermint/state_machine_context_test.go
  consensus/tendermint/tendermint_test.go
  consensus/tendermint/timeout_test.go
  consensus/tendermint/wal_test.go
  consensus/types/types.go
Labels: Tendermint

#2355 feat(trie): implement new trie architecture with separated node types
  core/trie2/collector.go
  core/trie2/databasetest.go
  core/trie2/errors.go
  core/trie2/hasher.go
  core/trie2/node_reader.go
  core/trie2/proof.go
  core/trie2/proof_test.go
  core/trie2/tracer.go
  core/trie2/trie.go
  core/trie2/trie_test.go
  core/trie2/triedb/database.go
  core/trie2/triedb/database/db.go
  core/trie2/triedb/empty.go
  core/trie2/triedb/pathdb/database.go
  core/trie2/triedb/pathdb/reader.go
  core/trie2/trienode/init_test.go
  core/trie2/trienode/node.go
  core/trie2/trienode/node_enc.go
  core/trie2/trienode/node_enc_test.go
  core/trie2/trienode/nodeset.go
  core/trie2/trienode/rawnode.go
  core/trie2/trienode/trienode_test.go
  core/trie2/trieutils/accessors.go
  core/trie2/trieutils/bitarray.go
  core/trie2/trieutils/bitarray_test.go
  core/trie2/trieutils/id.go
  core/trie2/trieutils/types.go
  db/buckets.go
  go.mod
  go.sum
  utils/orderedset.go
Labels: Refactor, State, 3 reviews, New DB

#2844 refactor: Remove precommits argument from Commit function
  consensus/integtest/blockchain.go
  consensus/tendermint/action_asserter_test.go
  consensus/tendermint/incoming_message_builder_test.go
  consensus/tendermint/rule_commit_value.go
  consensus/tendermint/rule_commit_value_test.go
  consensus/tendermint/state_machine_context_test.go
  consensus/tendermint/tendermint.go
  consensus/tendermint/tendermint_test.go
Labels: Tendermint

#2850 refactor: Use starknet types for integtest
  consensus/integtest/application.go
  consensus/integtest/blockchain.go
  consensus/integtest/broadcaster.go
  consensus/integtest/integ_test.go
  consensus/integtest/listener.go
  consensus/integtest/network.go
  consensus/integtest/node.go
  consensus/integtest/validator.go
Labels: Tendermint

#2804 Fix(RPC 0.8): V3 tx missing 'l1_data_gas' field handling
  .github/workflows/deploy-and-test.yaml
  .github/workflows/starknet-rs-tests.yml
  rpc/v8/block_test.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
Labels: Bug

#2841 feat: Add adapters for vote
  consensus/p2p/vote/vote.go
  consensus/p2p/vote/vote_test.go
Labels: Tendermint
