Repository NethermindEth/juno, pull requests merged in 2025-02, with the labels that each got.

#2409 Web socket updates
  jsonrpc/websocket.go
  jsonrpc/websocket_test.go
  mocks/mock_synchronizer.go
  rpc/block.go
  rpc/handlers.go
  rpc/helpers.go
  rpc/subscriptions.go
  rpc/subscriptions_test.go
  sync/sync.go
  sync/sync_test.go
Labels: high priority

#2397 Update blockifier
  adapters/core2p2p/receipt.go
  adapters/p2p2core/receipt.go
  core/transaction.go
  mocks/mock_vm.go
  node/throttled_vm.go
  rpc/v6/estimate_fee_test.go
  rpc/v6/handlers.go
  rpc/v6/simulation.go
  rpc/v6/simulation_test.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/estimate_fee_test.go
  rpc/v7/handlers_test.go
  rpc/v7/simulation.go
  rpc/v7/simulation_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v8/estimate_fee_test.go
  rpc/v8/handlers_test.go
  rpc/v8/simulation.go
  rpc/v8/simulation_pkg_test.go
  rpc/v8/simulation_test.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
  starknet/transaction.go
  vm/class.go
  vm/rust/Cargo.toml
  vm/rust/resources/versioned_constants_0_13_0.json
  vm/rust/resources/versioned_constants_0_13_1.json
  vm/rust/resources/versioned_constants_0_13_1_1.json
  vm/rust/resources/versioned_constants_0_13_2.json
  vm/rust/resources/versioned_constants_0_13_2_1.json
  vm/rust/resources/versioned_constants_0_13_3.json
  vm/rust/resources/versioned_constants_0_13_4.json
  vm/rust/src/jsonrpc.rs
  vm/rust/src/juno_state_reader.rs
  vm/rust/src/lib.rs
  vm/rust/src/versioned_constants.rs
  vm/rust/versioned_constants_13_2.json
  vm/trace.go
  vm/trace_test.go
  vm/transaction.go
  vm/vm.go
  vm/vm_ffi.h
  vm/vm_test.go
Labels: VM, dependencies, go, rust, high priority

#2434 Use semaphore for websocket connection limit
  jsonrpc/websocket.go
  jsonrpc/websocket_test.go
Labels: High priority

#2463 refactor: Reuse rpcv6 starknet_getNonce endpoint for v7 and v8
  rpc/handlers.go
  rpc/v7/storage.go
  rpc/v7/storage_test.go
  rpc/v8/handlers.go
  rpc/v8/storage.go
  rpc/v8/storage_test.go
Labels: RPC, Refactor, High priority

#2464 fix: Fix starknet_getStorageAt handler in edge cases
  rpc/v6/contract.go
  rpc/v6/contract_test.go
  rpc/v7/storage.go
  rpc/v7/storage_test.go
  rpc/v8/storage.go
  rpc/v8/storage_test.go
Labels: High priority

#2481 rpc subPendingTxns returns txn/hash individually instead of array
  rpc/v8/subscriptions.go
  rpc/v8/subscriptions_test.go
Labels: High priority

#2485 Fix missing L1 client error log
  rpc/v8/l1.go
  rpc/v8/l1_test.go
Labels: High priority

#2484 fix: starknet_getTransactionReceipt for pending transaction
  rpc/v7/transaction.go
  rpc/v7/transaction_test.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
Labels: RPC, High priority

#2469 Refactor: Reuse v6 starknet_getEvents handler for v7 and v8
  rpc/handlers.go
  rpc/v6/events.go
  rpc/v7/events.go
  rpc/v7/events_test.go
  rpc/v8/events.go
  rpc/v8/events_test.go
  rpc/v8/handlers.go
Labels: RPC, Refactor

#2459 refactor: Reuse rpcv6 starknet_syncing handler for v7 and v8
  rpc/handlers.go
  rpc/v7/sync.go
  rpc/v7/sync_test.go
  rpc/v8/handlers.go
  rpc/v8/sync.go
  rpc/v8/sync_test.go
Labels: RPC, Refactor

#2489 Remove `fmt.Println()`
  rpc/v6/simulation.go
Labels: High priority

#2492 fix(rpc): typo in err message
  rpc/v8/l1.go
Labels: typo

#2483 add validation for rpcv8.Transaction Resource bounds
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
  validator/validator.go
Labels: RPC, High priority

#2457 fix: Use INSUFFICIENT_RESOURCES_FOR_VALIDATE instead of INSUFFICIENT_MAX_FEE in v8
  clients/gateway/gateway.go
  rpc/rpccore/rpccore.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
Labels: High priority

#2455 rpc: handle the entrypoint not found error
  mocks/mock_vm.go
  node/throttled_vm.go
  rpc/rpccore/rpccore.go
  rpc/v6/estimate_fee.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/estimate_fee.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v8/estimate_fee.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
  utils/slices.go
  vm/rust/src/lib.rs
  vm/vm.go
  vm/vm_test.go
Labels: RPC, rust, High priority

#2502 fix: Cyclic dependencies when setting up pending subscription
  blockchain/blockchain.go
  node/node.go
Labels: High priority

#2503 refactor: Use pointer for optional block number in FilteredEvent
  blockchain/event_filter.go
  rpc/v6/events.go
  rpc/v8/subscriptions.go
  rpc/v8/subscriptions_test.go
Labels: High priority

#2515 Upgrade blockifier to 0.14.0-rc.1 and related dependencies
  starknet/compiler/rust/Cargo.toml
  vm/rust/Cargo.toml
  vm/rust/resources/versioned_constants_0_13_0.json
  vm/rust/resources/versioned_constants_0_13_1.json
  vm/rust/resources/versioned_constants_0_13_1_1.json
  vm/rust/resources/versioned_constants_0_13_2.json
  vm/rust/resources/versioned_constants_0_13_2_1.json
  vm/rust/resources/versioned_constants_0_13_3.json
  vm/rust/resources/versioned_constants_0_13_4.json
Labels: High priority

#2510 fix: Emit pending transaction events
  blockchain/event_filter.go
  clients/feeder/testdata/sepolia/block/56378.json
  clients/feeder/testdata/sepolia/signature/56378.json
  rpc/v8/subscriptions.go
  rpc/v8/subscriptions_test.go
Labels: High priority

#2521 Add docs for v0.13.0
  README.md
  docs/versioned_docs/version-0.13.0/_config-options.md
  docs/versioned_docs/version-0.13.0/configuring.md
  docs/versioned_docs/version-0.13.0/faq.md
  docs/versioned_docs/version-0.13.0/hardware-requirements.md
  docs/versioned_docs/version-0.13.0/intro.md
  docs/versioned_docs/version-0.13.0/json-rpc.md
  docs/versioned_docs/version-0.13.0/monitoring.md
  docs/versioned_docs/version-0.13.0/plugins.md
  docs/versioned_docs/version-0.13.0/running-juno.md
  docs/versioned_docs/version-0.13.0/running-on-gcp.md
  docs/versioned_docs/version-0.13.0/running-p2p.md
  docs/versioned_docs/version-0.13.0/snapshots.md
  docs/versioned_docs/version-0.13.0/staking-validator.md
  docs/versioned_docs/version-0.13.0/updating.md
  docs/versioned_docs/version-0.13.0/websocket.md
  docs/versioned_sidebars/version-0.13.0-sidebars.json
  docs/versions.json
Labels: High priority

#2544 fix: RPC v0.8 now doesn't support broadcasted transaction less than v3
  node/node.go
  rpc/v8/transaction.go
  rpc/v8/transaction_test.go
  validator/validator.go
Labels: High priority

#2575 fix(rpc v6 and v7): conversion from core.ResourceL1DataGas unsupported
  rpc/v6/transaction.go
  rpc/v6/transaction_test.go
  rpc/v7/transaction.go
  rpc/v7/transaction_test.go
  vm/rust/src/execution.rs
Labels: Bug, High priority

#2555 fix rpc: handle EntryPointNotFound error correctly
  vm/rust/src/lib.rs
  vm/vm.go
  vm/vm_test.go
Labels: Bug, High priority

#2566 fix(rpc): Functions in the rpc package were sending the wrong version to vm.Call
  adapters/sn2core/sn2core.go
  adapters/sn2core/sn2core_test.go
  clients/feeder/testdata/sepolia/class/0x3cc90db763e736ca9b6c581ea4008408842b1a125947ab087438676a7e40b7b.json
  clients/feeder/testdata/sepolia/compiled_class/0x3cc90db763e736ca9b6c581ea4008408842b1a125947ab087438676a7e40b7b.json
  core/class.go
  core/class_test.go
  rpc/v6/handlers_test.go
  rpc/v6/trace.go
  rpc/v6/trace_test.go
  rpc/v7/handlers_test.go
  rpc/v7/trace.go
  rpc/v7/trace_test.go
  rpc/v8/handlers_test.go
  rpc/v8/trace.go
  rpc/v8/trace_test.go
  utils/slices.go
  vm/class.go
  vm/class_test.go
  vm/rust/src/lib.rs
  vm/vm_test.go
Labels: Bug, High priority
